ngrok:
    authkey: ENC[AES256_GCM,data:8jzrdRur4A==,iv:97JJNoOWRmkYVfjkocbJaWsKMHrMYdvGuYvjP0NCAxU=,tag:ogSogDXzV7UTqFVfYlGsLw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19klm22jfa5d32hjaly2tyraf5hde94kxsl4a94795d99vnm5f4hqkz669p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOVGpkZW1oSUVQZXV6cXA0
            citSWld6T1V5dFNvcGowWmZTTmkxWHZJbFdZCjAyUS9UOEZ3cVJJMUNRaGp3S0U3
            eExMNWJFY1l0bFhMOGJETnR0ejRqNjgKLS0tIDFicDB2dncrYkU5L2FZSVNaRFhn
            RkJKZjBGLzBvQm0yQXlkZkRBcEZZaGMKXnIRph0A8W20N/je9jWrSztBBik+FbWe
            MtVy1lJqGQRlpQsluI6u/qR946gvqAbSsfvIaZ1Q4845uZvmfupwAg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10v5dg34ud2fw0dp2xzl0qygpkau8ujexcrq7atzq4deawhuf8qsqpwl029
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDVjJUT2M3T3ZRdkpFSVcr
            WnpjUmJPM2VXYlpwQ1UzT0tSNkVOR2lmOGc4Cml5ZnY1c3loSy82WlA2MWdEK2U3
            d0FkNUpuNGxTREExaFc2MXJkMnh4NlkKLS0tIHlraGt5RzhuTmFMemMrOC9lOFNt
            eDdXYzdsemRpdkpRNkxDMUZFUE5mWVEKv7VoZBGs+sifuh5XxZ4Rrv0dg3nfq+de
            oFxbaueZHcYAYlWh74d+r3sBPrITZ1NfXFFmaArezyX6xTjezEuJTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-02T19:05:50Z"
    mac: ENC[AES256_GCM,data:m+bwePhyqYx+N70q2M51NO5lqfr6NO3oJ8lorZcPKo0rgewPkPKcbslYCdgFb+GnyEoV9BPD9MD87nkVPEBgEC4f3idhtsqwobXJAfODG8OykCqub2oT9OY8t8NxpMqhKFI/LbXk1pPqO6FMQfBLh0y8gEbLUWt2AYeVZiEaOxM=,iv:yde/Yb9WzmknBTegHfMMri22n/3e4vAPvqMxdp/+oHs=,tag:m3WcrlmLhN3kmb1Y11wr4Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
